In [1]:
import numpy as np

####  Excercise 1:Replace all odd/even number in given numpy array with its negative

In [2]:
exercise1=np.random.randint(10,50,size=(20))
exercise1

array([27, 13, 47, 27, 39, 24, 24, 35, 42, 12, 45, 20, 33, 48, 23, 23, 34,
       33, 29, 15])

In [3]:
exercise1[exercise1%2==0]*=-1
exercise1

array([ 27,  13,  47,  27,  39, -24, -24,  35, -42, -12,  45, -20,  33,
       -48,  23,  23, -34,  33,  29,  15])

In [4]:
exercise1[exercise1%2==1]*=-1
exercise1

array([-27, -13, -47, -27, -39, -24, -24, -35, -42, -12, -45, -20, -33,
       -48, -23, -23, -34, -33, -29, -15])

#### Excerise 2 :Create a numpy array from a csv file

In [5]:
iris_data=np.genfromtxt('iris.csv',delimiter=',',skip_header=1,dtype=str,
                        usecols=[0,1,2,3,4])
iris_data

array([['5.1', '3.5', '1.4', '0.2', 'setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'setosa'],
       ['5.1', '3.8', '1.5', '0.3', 'setosa'],
       ['5.4', '3.4', '1.7', '0.2', 'setosa'],
       ['5.1'

#### Exercise 3:Find the count of unique values in a numpy array

In [6]:
iris_data=np.genfromtxt('iris.csv',delimiter=',',skip_header=1,dtype=str,
                        usecols=[4])

np.unique(iris_data,return_counts=True)

(array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 array([50, 50, 50], dtype=int64))

#### Excercise 4: Filter numpy array based on two or more conditions

In [7]:
iris_data=np.genfromtxt('iris.csv',delimiter=',',skip_header=1,dtype=float,
                        usecols=[0,1,2,3])

iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris_data[(iris_data[:,2]>1.5)&(iris_data[:,0]<5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

#### Exercise 5: Find if given array has any null/nan values.

In [9]:
np.isnan(iris_data).any()

False

In [10]:
iris_data[(iris_data[:,:]==3.4) | (iris_data[:,:]==1.7)]=np.nan
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, nan, 0.4],
       [4.6, nan, 1.4, 0.3],
       [5. , nan, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, nan, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, nan, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, nan, nan, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, nan, 0.5],
       [4.8, nan, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , nan, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, nan, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, nan, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris_data[(iris_data==3.4) | (iris_data==1.7)]=np.nan
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, nan, 0.4],
       [4.6, nan, 1.4, 0.3],
       [5. , nan, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, nan, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, nan, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, nan, nan, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, nan, 0.5],
       [4.8, nan, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , nan, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, nan, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, nan, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
np.isnan(iris_data).sum(axis=0)

array([ 0, 12,  4,  2])

#### Exercise 6:Find the most frequent value in a numpy array

In [13]:
value,count=np.unique(iris_data[:,1],return_counts=True)

value,count

(array([2. , 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3,
        3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.4, nan]),
 array([ 1,  3,  4,  3,  8,  5,  9, 14, 10, 26, 11, 13,  6,  6,  4,  3,  6,
         2,  1,  1,  1,  1, 12], dtype=int64))

In [14]:
for i in range(iris_data.shape[1]):
    value,count=np.unique(iris_data[:,i],return_counts=True)
    print(value[np.argmax(count)])

5.0
3.0
1.4
0.2


In [15]:
np.unique(iris_data[:,1],return_counts=True)[1]

array([ 1,  3,  4,  3,  8,  5,  9, 14, 10, 26, 11, 13,  6,  6,  4,  3,  6,
        2,  1,  1,  1,  1, 12], dtype=int64)

#### Exercise 7:Find index position of first occurance of value >a given value

In [16]:
# first_occurance of a value >2.3 in each columns

In [17]:
iris_data=np.genfromtxt('iris.csv',delimiter=',',skip_header=1,dtype=float,
                        usecols=[0,1,2,3])

iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
for i in range(iris_data.shape[1]):
    print(np.argmax(iris_data[:,i]>2.3))
    

0
0
50
100


In [19]:
iris_data[iris_data[:,3]>2.3],np.argmax(iris_data[:,2]>2.3)

(array([[6.3, 3.3, 6. , 2.5],
        [7.2, 3.6, 6.1, 2.5],
        [5.8, 2.8, 5.1, 2.4],
        [6.3, 3.4, 5.6, 2.4],
        [6.7, 3.1, 5.6, 2.4],
        [6.7, 3.3, 5.7, 2.5]]),
 50)

In [20]:
for i in range(iris_data.shape[1]):
    print(np.argmax(iris_data[:,i]>2.3))

0
0
50
100


In [21]:
for i in range(iris_data.shape[1]):
    print(iris_data[iris_data[:,i]>2.3][0][0],np.argwhere(iris_data[:,i]>2.3)[0])


5.1 [0]
5.1 [0]
7.0 [50]
6.3 [100]



#### Exercise 8:write a program that accepts a sentence and find value counts of letter and digits.Input value will be supplied to program

In [22]:
str=input("Enter the string:")
dict={"letter":0,"digit":0}
for i in str:
    if(i.isdigit()):
        dict["digit"]+=1
    elif(i.isalpha()):
        dict["letter"]+=1
    
print('Letters: ',dict['letter'])
print('Digits: ',dict['digit'])

Enter the string:Hello python
Letters:  11
Digits:  0
